config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :article_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article_type.rb
class ArticleType < ApplicationRecord
  def test_method
    'test'
  end

  def test_method_two
    'test2'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :hello

  def hello; end

  def new_method; end

  def dummy; end
end

app/controllers/article_types_controller.rb
class ArticleTypesController < ApplicationController
  before_action :set_article_type, only: [:show, :edit, :update, :destroy]

  # GET /article_types
  # GET /article_types.json
  def index
    @article_types = ArticleType.all
  end

  # GET /article_types/1
  # GET /article_types/1.json
  def show
  end

  # GET /article_types/new
  def new
    @article_type = ArticleType.new
  end

  # GET /article_types/1/edit
  def edit
  end

  # POST /article_types
  # POST /article_types.json
  def create
    @article_type = ArticleType.new(article_type_params)

    respond_to do |format|
      if @article_type.save
        format.html { redirect_to @article_type, notice: 'Article type was successfully created.' }
        format.json { render :show, status: :created, location: @article_type }
      else
        format.html { render :new }
        format.json { render json: @article_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /article_types/1
  # PATCH/PUT /article_types/1.json
  def update
    respond_to do |format|
      if @article_type.update(article_type_params)
        format.html { redirect_to @article_type, notice: 'Article type was successfully updated.' }
        format.json { render :show, status: :ok, location: @article_type }
      else
        format.html { render :edit }
        format.json { render json: @article_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /article_types/1
  # DELETE /article_types/1.json
  def destroy
    @article_type.destroy
    respond_to do |format|
      format.html { redirect_to article_types_url, notice: 'Article type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article_type
      @article_type = ArticleType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_type_params
      params.require(:article_type).permit(:name, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render json: { response: 'This is a new response' }, status: :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/article_types/_form.html.haml
= form_with model: @article_type, remote: true do |f|
  - if @article_type.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article_type.errors.count, "error")} prohibited this article_type from being saved:"
      %ul
        - @article_type.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name, lable: 'lable'
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/article_types/edit.html.haml
%h1 Editing article_type

= render 'form'

= link_to 'Show', @article_type
\|
= link_to 'Back', article_types_path

app/views/article_types/index.html.haml
%h1 Listing article_types

%table
  %thead
    %tr
      %th Name
      %th Description
      %th
      %th
      %th

  %tbody
    - @article_types.each do |article_type|
      %tr
        %td= article_type.name
        %td= article_type.description
        %td= link_to 'Show', article_type
        %td= link_to 'Edit', edit_article_type_path(article_type)
        %td= link_to 'Destroy', article_type, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Article type', new_article_type_path

app/views/article_types/new.html.haml
%h1 New article_type

= render 'form'

= link_to 'Back', article_types_path

app/views/article_types/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @article_type.name
%p
  %b Description:
  = @article_type.description

= link_to 'Edit', edit_article_type_path(@article_type)
\|
= link_to 'Back', article_types_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>